ALTER TABLE CHUC_VU
    ADD IS_DELETED NUMBER(1) DEFAULT 0;
/
ALTER TABLE CHUC_VU
    ADD NGAY_TAO DATE DEFAULT CURRENT_DATE;
/
ALTER TABLE CHUC_VU
    ADD NGAY_SUA DATE;
/
ALTER TABLE CHUC_VU
    ADD NGUOI_SUA VARCHAR(4000);
/
ALTER TABLE CHUC_VU
    ADD NGUOI_TAO VARCHAR(4000);